name: Binder Badge
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Example of message!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
