name: Binder Badge
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: "[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${{ github.event.pull_request.head.user.login }}/${context.repo.repo}/${{ github.event.pull_request.head.ref }}?urlpath=%2Fdesktop) :point_left: Launch a binder instance on this branch"
